# Generated by Django 3.2.12 on 2023-02-16 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_auto_20230216_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='motorcycle',
            old_name='dateOfPurchase',
            new_name='pub_date',
        ),
    ]
